#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Marc de Ferranti"
email = "mezdef@gmail.com"

[merge-tools.nvimdiff]
program = "nvim"

[ui]
merge-tool = "nvimdiff"
editor = "nvim"
diff-editor = "nvim"

[colors]
# Custom colors (catppucin)
# colors.mauve = "#cba6f7"
# colors.lavender = "#b4befe"

change_id = { fg = "#cba6f7" }
commit_id = { fg = "red" }
# Unique prefixes and the rest for change & commit ids
prefix = { bold = true }
rest = "bright black"

timestamp = "bright black"
working_copies = "green"
bookmark = "blue"
bookmarks = "blue"
local_bookmarks = "blue"
remote_bookmarks = "blue"
tag = "blue"
tags = "blue"

config_list = "cyan"
